[package]
name = "main"
version = "0.1.0"
authors = ["jslupicki <jan@slupicki.com>"]
edition = "2018"

[dependencies]
dao = { path = "../dao" }
rest = { path = "../rest" }
log = "0.4.6"
log4rs = "0.8.3"
actix-web = "0.7.19"
